# Generated by Django 4.1.7 on 2023-03-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='year_olds',
            field=models.IntegerField(default=15),
        ),
    ]
